"""Measure how well `chunk_document` preserves CUAD answer spans (test split).

Writes/replaces the "## Chunking" section of docs/data/cuad.md.
Usage: uv run python scripts/chunk_stats.py  (after scripts/download_cuad.py)
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

from docent.ingest.chunking import chunk_document

ROOT = Path(__file__).resolve().parent.parent
TEST_JSON = ROOT / "data" / "raw" / "cuad" / "test.json"
REPORT = ROOT / "docs" / "data" / "cuad.md"
SECTION = "## Chunking"
MAX_CHARS = [1000, 1500, 2000]
OVERLAP = 200

Doc = tuple[str, str, list[tuple[int, int]]]


def load_docs(path: Path) -> list[Doc]:
    with path.open(encoding="utf-8") as f:
        squad = json.load(f)
    docs: list[Doc] = []
    for doc in squad["data"]:
        for i, para in enumerate(doc["paragraphs"]):
            spans = [
                (a["answer_start"], a["answer_start"] + len(a["text"]))
                for qa in para["qas"]
                for a in qa["answers"]
            ]
            docs.append((f"{doc['title']}#{i}", para["context"], spans))
    return docs


def evaluate(docs: list[Doc], max_chars: int) -> list[str]:
    counts: list[int] = []
    n_spans = n_contained = n_too_long = 0
    for doc_id, context, spans in docs:
        chunks = chunk_document(doc_id, context, max_chars=max_chars, overlap_chars=OVERLAP)
        counts.append(len(chunks))
        for start, end in spans:
            n_spans += 1
            n_too_long += end - start > max_chars
            n_contained += any(c.char_start <= start and end <= c.char_end for c in chunks)
    return [
        f"{max_chars:,}",
        f"{statistics.median(counts):g}",
        f"{max(counts):,}",
        f"{n_contained:,} / {n_spans:,} ({100 * n_contained / n_spans:.2f}%)",
        f"{n_too_long:,}",
    ]


def render(rows: list[list[str]]) -> str:
    header = [
        "max_chars",
        "chunks/contract (median)",
        "chunks/contract (max)",
        "answer spans fully inside ≥1 chunk",
        "spans longer than max_chars",
    ]
    lines = [
        SECTION,
        "",
        f"Generated by `scripts/chunk_stats.py` on `test.json`, `overlap_chars={OVERLAP}`.",
        "",
        "| " + " | ".join(header) + " |",
        "|" + "---|" * len(header),
        *("| " + " | ".join(r) + " |" for r in rows),
        "",
    ]
    return "\n".join(lines)


def upsert_section(report: str, section: str) -> str:
    """Replace an existing `## Chunking` section (up to the next `## `) or append it."""
    head, sep, tail = report.partition(SECTION)
    if not sep:
        return report.rstrip("\n") + "\n\n" + section
    nxt = tail.find("\n## ")
    rest = tail[nxt + 1 :] if nxt != -1 else ""
    return head + section + ("\n" + rest if rest else "")


def main() -> int:
    if not TEST_JSON.exists():
        print(f"missing {TEST_JSON}; run scripts/download_cuad.py first", file=sys.stderr)
        return 1
    docs = load_docs(TEST_JSON)
    section = render([evaluate(docs, m) for m in MAX_CHARS])
    print(section)

    existing = REPORT.read_text(encoding="utf-8") if REPORT.exists() else ""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(upsert_section(existing, section), encoding="utf-8")
    print(f"updated {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
