"""Exploration report for CUAD (SQuAD-format JSON) -> docs/data/cuad.md.

Reads raw JSON with the stdlib only; context/answer strings are never normalised
except in the explicit "stripped" span check.

Usage: uv run python scripts/explore_cuad.py  (after scripts/download_cuad.py)
"""

from __future__ import annotations

import json
import math
import re
import statistics
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "raw" / "cuad"
REPORT = ROOT / "docs" / "data" / "cuad.md"
SPLITS = {"train": "train_separate_questions.json", "test": "test.json"}

PAGE_PATTERNS: dict[str, re.Pattern[str]] = {
    "`Page N` / `Page N of M`": re.compile(r"\bPage\s+\d+(?:\s+of\s+\d+)?\b", re.IGNORECASE),
    "`- N -`": re.compile(r"(?:^|\s)-\s?\d{1,3}\s?-(?:\s|$)"),
    "standalone number line": re.compile(r"^[ \t]*\d{1,3}[ \t]*$", re.MULTILINE),
}


@dataclass
class SplitStats:
    titles: set[str] = field(default_factory=set)
    context_lengths: list[int] = field(default_factory=list)
    n_qas: int = 0
    n_qas_no_answer: int = 0
    questions: set[str] = field(default_factory=set)
    categories: set[str] = field(default_factory=set)
    n_form_feed: int = 0
    page_hits: dict[str, int] = field(default_factory=lambda: dict.fromkeys(PAGE_PATTERNS, 0))
    n_any_page_marker: int = 0
    n_answers: int = 0
    n_span_ok_raw: int = 0
    n_span_ok_stripped: int = 0
    n_answer_padded: int = 0
    n_context_padded: int = 0


def percentile(values: list[int], p: float) -> int:
    """Nearest-rank percentile (p in [0, 100])."""
    if not values:
        raise ValueError("percentile of empty list")
    ordered = sorted(values)
    rank = max(1, math.ceil(p / 100 * len(ordered)))
    return ordered[rank - 1]


def span_matches(context: str, start: int, text: str) -> bool:
    return context[start : start + len(text)] == text


def category_of(qa_id: str, question: str) -> str:
    """CUAD ids are `<title>__<Category>` (train adds `_<n>`); else use the quoted name."""
    m = re.search(r"__(.+?)(?:_\d+)?$", qa_id)
    if m:
        return m.group(1)
    m = re.search(r'"([^"]+)"', question)
    return m.group(1) if m else question


def analyse(squad: dict[str, Any]) -> SplitStats:
    s = SplitStats()
    for doc in squad["data"]:
        s.titles.add(doc["title"])
        for para in doc["paragraphs"]:
            context: str = para["context"]
            stripped_context = context.strip()
            s.context_lengths.append(len(context))
            s.n_context_padded += context != stripped_context
            if "\f" in context:
                s.n_form_feed += 1
            any_marker = "\f" in context
            for name, pattern in PAGE_PATTERNS.items():
                if pattern.search(context):
                    s.page_hits[name] += 1
                    any_marker = True
            s.n_any_page_marker += any_marker

            for qa in para["qas"]:
                s.n_qas += 1
                s.questions.add(qa["question"])
                s.categories.add(category_of(qa["id"], qa["question"]))
                answers = qa["answers"]
                if not answers:
                    s.n_qas_no_answer += 1
                for ans in answers:
                    text: str = ans["text"]
                    start: int = ans["answer_start"]
                    s.n_answers += 1
                    s.n_span_ok_raw += span_matches(context, start, text)
                    s.n_span_ok_stripped += span_matches(stripped_context, start, text.strip())
                    s.n_answer_padded += text != text.strip()
    return s


def pct(num: int, den: int) -> str:
    return f"{100 * num / den:.2f}%" if den else "n/a"


def table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def render(stats: dict[str, SplitStats]) -> str:
    names = list(stats)
    hdr = ["metric", *names]

    def row(label: str, fn: Any) -> list[str]:
        return [label, *(str(fn(stats[n])) for n in names)]

    train, test = stats["train"].titles, stats["test"].titles
    out = [
        "# CUAD v1 — data exploration",
        "",
        "Generated by `scripts/explore_cuad.py` from `data/raw/cuad/` "
        f"({', '.join(f'`{f}`' for f in SPLITS.values())}). Do not edit by hand.",
        "",
        "## a) Contracts and QA items",
        "",
        table(
            hdr,
            [
                row("contracts (distinct titles)", lambda s: f"{len(s.titles):,}"),
                row("contexts (paragraphs)", lambda s: f"{len(s.context_lengths):,}"),
                row("QA items", lambda s: f"{s.n_qas:,}"),
                row("answer spans", lambda s: f"{s.n_answers:,}"),
            ],
        ),
        "",
        table(
            ["title overlap", "count"],
            [
                ["train ∩ test", str(len(train & test))],
                ["train only", str(len(train - test))],
                ["test only", str(len(test - train))],
            ],
        ),
        "",
        "## b) Context length (chars, raw)",
        "",
        table(
            hdr,
            [
                row("min", lambda s: f"{min(s.context_lengths):,}"),
                row("median", lambda s: f"{statistics.median(s.context_lengths):,.0f}"),
                row("p95", lambda s: f"{percentile(s.context_lengths, 95):,}"),
                row("max", lambda s: f"{max(s.context_lengths):,}"),
            ],
        ),
        "",
        "## c) Page markers (contexts containing ≥1 match)",
        "",
        table(
            hdr,
            [
                row("form feed `\\f`", lambda s: s.n_form_feed),
                *(row(name, lambda s, name=name: s.page_hits[name]) for name in PAGE_PATTERNS),
                row(
                    "any of the above",
                    lambda s: (
                        f"{s.n_any_page_marker} ({pct(s.n_any_page_marker, len(s.context_lengths))})"
                    ),
                ),
            ],
        ),
        "",
        "## d) Questions / categories",
        "",
        table(
            hdr,
            [
                row("distinct question strings", lambda s: len(s.questions)),
                row("distinct categories", lambda s: len(s.categories)),
                row(
                    "QA items with zero answers",
                    lambda s: f"{s.n_qas_no_answer:,} ({pct(s.n_qas_no_answer, s.n_qas)})",
                ),
            ],
        ),
        "",
        "## e) Answer span validity",
        "",
        "`context[start:start+len(text)] == text`. *Raw* uses the strings as stored; "
        "*stripped* applies `.strip()` to both context and answer while keeping "
        "`answer_start` unchanged — the gap between the two is offset drift caused by "
        "whitespace normalisation.",
        "",
        table(
            hdr,
            [
                row(
                    "valid (raw)",
                    lambda s: (
                        f"{s.n_span_ok_raw:,} / {s.n_answers:,} ({pct(s.n_span_ok_raw, s.n_answers)})"
                    ),
                ),
                row(
                    "valid (stripped)",
                    lambda s: (
                        f"{s.n_span_ok_stripped:,} / {s.n_answers:,} ({pct(s.n_span_ok_stripped, s.n_answers)})"
                    ),
                ),
                row(
                    "answers with leading/trailing whitespace",
                    lambda s: f"{s.n_answer_padded:,} ({pct(s.n_answer_padded, s.n_answers)})",
                ),
                row(
                    "contexts with leading/trailing whitespace",
                    lambda s: (
                        f"{s.n_context_padded:,} ({pct(s.n_context_padded, len(s.context_lengths))})"
                    ),
                ),
            ],
        ),
        "",
    ]
    return "\n".join(out)


def main() -> int:
    stats: dict[str, SplitStats] = {}
    for split, filename in SPLITS.items():
        path = DATA_DIR / filename
        if not path.exists():
            print(f"missing {path}; run scripts/download_cuad.py first", file=sys.stderr)
            return 1
        with path.open(encoding="utf-8") as f:
            stats[split] = analyse(json.load(f))

    report = render(stats)
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(report)
    print(f"wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
